### ISSUE TITLE
Add New Configuration Pane to LR Panel

### ISSUE THREAD

**Issue by jasonhoekstra** [learningtapestry/drupal7-learning-registry#15]
Add a configuration pane (portion) to the LR Configuration Panel:

1. Delete the "Public Taxonomy Tags as Keywords" option.
2. Add a new section to the called "LRMI/DCMI Alignment"
3. Add four fields to configure using the following logic:
  1. Standards, Grade Levels, Subjects, Learning Resource Type
  2. Each term provides a drop down to select "Taxonomy Term", "Constant Variable", "Field" or "None"
    1. If "Taxonomy Term", present drop down to select a Drupal taxonomy term.  If term == Standards or Grade Levels, also present "Framework:" text field.
    2. If "Learning Resource Type", present "Value:" text field 

![drupal7modulemock](https://cloud.githubusercontent.com/assets/442930/6582788/183a3f9e-c736-11e4-9c55-d1f545a6358a.png)

**Comment by Kirmish** [comment]
Hi Jason,

"Constant variable" and "Field" in the dropdown, what a difference?
If "Taxonomy Term" selected in the "Learning Resource Type", what should be shown? "Taxonomy term" dropdown and "Value" text field?

Thanks,
Kirill

**Comment by Kirmish** [comment]
Jason, please pull the commit and look to the lr admin settings page. What I should change?

Thanks,
Kirill

**Comment by jasonhoekstra** [comment]
Hi Kirill -

This is looking good and heading in the right direction.

A few notes:

1.)  The taxonomy term drop down:

![image](https://cloud.githubusercontent.com/assets/442930/6827181/5c6f9c3e-d2dc-11e4-9103-734cad92c8e6.png)

Should be the list of taxonomy terms defined in Drupal:

![image](https://cloud.githubusercontent.com/assets/442930/6827178/5938a3c6-d2dc-11e4-8809-214e1ace9a11.png)

2.)  It looks like the settings aren't reappearing after the user clicks "Save configuration"

Settings:

![image](https://cloud.githubusercontent.com/assets/442930/6827628/f1eb7236-d2de-11e4-8731-84a8987acdc4.png)

After save:

![image](https://cloud.githubusercontent.com/assets/442930/6827664/294de43e-d2df-11e4-9344-c47e9fd23863.png)

3.)  Let's delete the field option for now.

**Comment by Kirmish** [comment]
Hi Jason,

#15 done, please test. One thing - I don't quite understand what you mean about list of taxonomy terms - it was done in the last https://github.com/learningtapestry/drupal7-learning-registry/commit/eba66627ece9a970d6d8a789fb6fe2ba0f9ab09d - All taxonomy terms from the all vocabularies found in the "Taxonomy" dropdown (Look attachment)
![screenshot_2](https://cloud.githubusercontent.com/assets/10742849/6880353/7aa860e2-d53d-11e4-8382-b8a2a878f544.png)

**Comment by jasonhoekstra** [comment]
Hi Kirill -

On the Taxonomy Term, I may be using the wrong language for this.  Maybe "Vocabulary Name" is a better way to define this?  For the drop down, I'd like the user select from the defined vocabulary sets, for example "Standards", "Common Core" and "Tags" as seen below:

![image](https://cloud.githubusercontent.com/assets/442930/6882890/42b28d28-d56c-11e4-9537-2df7a30263ab.png)

Once the user selects the Vocab Name/term, we'll use that data to populate the LR JSON envelope with the values associated with the node.

Does that make more sense?

Jason

**Comment by Kirmish** [comment]
Hi Jason,

Changed.

Regards,
Kirill

**Comment by jasonhoekstra** [comment]
Looks good, thanks @Kirmish !
