### ISSUE TITLE
Update metadata for create and update messages -- Subjects or Learning Resource Type

### ISSUE THREAD

**Issue by jasonhoekstra** [learningtapestry/drupal7-learning-registry#17]
For Subjects or Learning Resource Type, emit the following into the LR metadata when standards or grade level taxonomy terms are present:

```
subjects: [ ---CONSTANT VARIABLE--- or ---TAXONOMY TERMS--- ],
learningResourceType: [ ---CONSTANT VARIABLE--- or ---TAXONOMY TERMS--- ]
```

**Comment by Kirmish** [comment]
Hi Jason,

Please check.

Regards,
Kirill

**Comment by jasonhoekstra** [comment]
I'm now getting an error on publish, any idea what this could be about?

![image](https://cloud.githubusercontent.com/assets/442930/6998515/00cf9868-dbb3-11e4-91f3-964eec3e8b5a.png)

My configuration is:

![image](https://cloud.githubusercontent.com/assets/442930/6998528/3d643ff4-dbb3-11e4-87ea-7d8927fde83b.png)

**Comment by Kirmish** [comment]
Hi Jason,

Fixed.

Regards,
Kirill
